---
- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl
  when:
    - not rke2_reboot

- name: Restart containerd
  ansible.builtin.service:
    state: restarted
    name: containerd
  when:
    - not rke2_reboot

- name: Restart fapolicyd
  ansible.builtin.service:
    state: restarted
    name: fapolicyd
  when:
    - not rke2_reboot

- name: Restart rke2-server
  ansible.builtin.service:
    state: restarted
    enabled: true
    name: rke2-server
  throttle: 1
  when:
    - not rke2_reboot
    - ("rke2_servers" in group_names)

- name: Restart rke2-agent
  ansible.builtin.service:
    state: restarted
    enabled: true
    name: rke2-agent
  throttle: 1
  when:
    - not rke2_reboot
    - ("rke2_agents" in group_names)

- name: Reload NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: reloaded
  when:
    - not rke2_reboot

- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 300
  throttle: 1
  when:
    - rke2_reboot

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
    when: "'rke2_servers' in group_names"

- name: Restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
    when: "'rke2_agents' in group_names"
