---

# inventory/hosts.yml - Fixed version
all:
  vars:
    rke2_disable_components:
      - rke2-canal
      - rke2-calico
      - rke2-cilium
      - rke2-flannel
    # Proxy
    http_proxy: "http://10.31.10.15:3128"
    https_proxy: "http://10.31.10.15:3128"
    no_proxy: "localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"

    # Network configuration
    pod_cidr: "10.31.45.0/24"  # Custom pod network
    service_cidr: "10.31.46.0/24"
    cluster_domain: "cluster.local"
    ncp_namespace: "nsx-system" 
    rke2_service_cidr: "172.17.0.0/16"  # Custom service network
    rke2_cni: [none]                   # CNI plugin choice
    rke2_token: "K10f8e7c4b9a2d1f3e6c8a5b7d9f2e4c6a8b5d7f9e2c4a6b8d5f7e9c2a4b6d8f5a7c9e"

    # NSX-T specific variables (username/password auth)
    nsx_manager_host: "nsxt.pcc-147-135-35-37.ovh.us"
    nsx_username: "kubetest"
    nsx_password: "P8Tj9tqq6G0ruHA8j9d3"
    nsx_cluster_name: "k8s-cluster-01"
    nsx_tier0_router: "T0-Router"
    nsx_overlay_tz: "overlay-tz"
    nsx_vlan_tz: "vlan-tz"
    nsx_edge_cluster: "edge-cluster-01"

    # NSX Container Plugin specific settings (public images)
    ncp_image: "projects.registry.vmware.com/nsx/ncp:latest"
    ncp_node_agent_image: "projects.registry.vmware.com/nsx/ncp:latest"

    # SSH configuration
    ansible_user: chait
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become: true  # ADDED: Required for RKE2 installation
    # API Server binding configuration
    rke2_bind_address: "0.0.0.0"  # Bind to all interfaces
    rke2_advertise_address: "{{ ansible_default_ipv4.address }}"  # Advertise actual IP
    # TLS SANs - important for external access
    rke2_tls_san:
      - "{{ ansible_default_ipv4.address }}"
      - "{{ ansible_hostname }}"
      - "{{ ansible_fqdn }}"
      - "0.0.0.0"
      - "127.0.0.1"
      - "localhost"
    # ADDED: RKE2 specific settings
    rke2_download_kubeconf: true
    rke2_download_kubeconf_path: "/tmp"
    rke2_kubernetes_api_server_host: "10.31.44.100"
    create_default_policies: false  # Set to true to create default network policies
    enable_antrea_features: true    # Enable additional Antrea features
  children:
    masters:
      hosts:
        master-01:
          ansible_host: 10.31.44.100
          rke2_node_ip: 10.31.44.100
        master-02:
          ansible_host: 10.31.44.101
          rke2_node_ip: 10.31.44.101
        master-03:
          ansible_host: 10.31.44.102
          rke2_node_ip: 10.31.44.102
    workers:
      hosts:
        worker-01:
          ansible_host: 10.31.44.111
          rke2_node_ip: 10.31.44.111
        worker-02:
          ansible_host: 10.31.44.112
          rke2_node_ip: 10.31.44.112
    rke2_servers:
      children:
        masters:  # Masters are the RKE2 servers
    rke2_agents:
      children:
        workers:  # Workers are the RKE2 agents
