all:
  children:
    servers:
      hosts:
        kube-it-control-001:
          ansible_host: 10.31.44.103
          node_ip: 10.31.44.103
        kube-it-control-002:
          ansible_host: 10.31.44.101
          node_ip: 10.31.44.101
        kube-it-control-003:
          ansible_host: 10.31.44.102
          node_ip: 10.31.44.102
    agents:
      hosts:
        kube-it-worker-001:
          ansible_host: 10.31.44.111
          node_ip: 10.31.44.111
        kube-it-worker-002:
          ansible_host: 10.31.44.112
          node_ip: 10.31.44.112

    rke2_servers:
      children:
        servers:
    rke2_agents:
      children:
        agents: