---

# - name: Cleanup sources
#   ansible.builtin.import_tasks: fix_repositories.yml

- name: Update apt cache
  ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600

- name: Install prerequisites
  ansible.builtin.apt:
      name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-kubernetes
      state: present

- name: Install snaps
  community.general.snap:
      name:
          - kubectl
      state: present
      classic: true

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'

- name: Add Docker repository
  ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      update_cache: true

- name: Update apt cache after adding repository
  ansible.builtin.apt:
      update_cache: true

- name: Install containerd
  ansible.builtin.apt:
      name: containerd.io
      state: present

- name: Create containerd configuration directory
  ansible.builtin.file:
      path: "/etc/containerd"
      state: directory
      mode: '0755'

- name: Generate default containerd configuration
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  args:
      creates: /etc/containerd/config.toml

- name: Configure containerd to use systemd cgroup driver
  ansible.builtin.lineinfile:
      path: /etc/containerd/config.toml
      regexp: '^\s*SystemdCgroup\s*='
      line: '            SystemdCgroup = true'
      insertafter: '.*\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\]'


- name: Configure containerd for RKE2 (optional)
  block:
      - name: Ensure containerd uses correct socket path for RKE2
        ansible.builtin.lineinfile:
            path: /etc/containerd/config.toml
            regexp: '^\s*address\s*='
            line: '  address = "/run/k3s/containerd/containerd.sock"'
            insertafter: '^\[grpc\]'
        become: true
        register: configure_for_rke2_changed
        notify: Restart containerd

- name: Create containerd socket directory
  ansible.builtin.file:
      path: /run/k3s/containerd
      state: directory
      mode: '0755'
  become: true
  when: configure_for_rke2 | default(false)

- name: Start and enable containerd service
  ansible.builtin.systemd:
      name: containerd
      state: started
      enabled: true
      daemon_reload: true

- name: Verify containerd is running
  ansible.builtin.systemd:
      state: started
      name: containerd
