---
- name: Setup Docker Hub secret
  kubernetes.core.k8s:
    name: dockerhub-secret
    namespace: default
    api_version: v1
    kind: Secret
    definition:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ {'auths': {'https://index.docker.io/v1/': {'username': 'piper41955', 'password': 'dckr_pat_kNFMGvjRG_l5Ro30GKT6-ELVFZk', 'email': 'your-email@example.com', 'auth': ('piper41955:dckr_pat_kNFMGvjRG_l5Ro30GKT6-ELVFZk' | b64encode)}}} | to_json | b64encode }}"
    kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
  remote_user: "chait"


- name: Patch default service account
  kubernetes.core.k8s:
    name: default
    namespace: default
    api_version: v1
    kind: ServiceAccount
    merge_type: strategic-merge
    definition:
      imagePullSecrets:
        - name: dockerhub-secret
    kubeconfig: "/etc/rancher/rke2/rke2.yaml"
  delegate_to: "{{ groups['masters'][0] }}"
  remote_user: "chait"
