- name: Install python deps
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-kubernetes
      - python3-yaml
      - python3-jsonpatch
    state: present

- name: Download Antrea manifest
  ansible.builtin.get_url:
    url: "https://github.com/antrea-io/antrea/releases/download/v2.3.0/antrea.yml"
    dest: /tmp/antrea-original.yml
    mode: '0644'
    timeout: 60

- name: Process Antrea manifest for RKE2
  ansible.builtin.template:
    src: antrea-config.yaml.j2
    dest: /tmp/antrea-rke2.yml
    mode: '0644'

- name: Apply Antrea configmap for CNI
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    src: /tmp/antrea-rke2.yml
    state: present
  delegate_to: "master-01"

- name: Apply Antrea CNI
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    src: /tmp/antrea-original.yml
    state: present
  delegate_to: "master-01"

- name: Wait for Antrea controller
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    api_version: apps/v1
    kind: Deployment
    name: antrea-controller
    namespace: kube-system
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300
  delegate_to: "master-01"

- name: Wait for Antrea agents
  kubernetes.core.k8s_info:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    api_version: apps/v1
    kind: DaemonSet
    name: antrea-agent
    namespace: kube-system
  register: antrea_ds
  delegate_to: "master-01"
  until: >
    antrea_ds.resources[0].status.numberReady is defined and
    antrea_ds.resources[0].status.numberReady == groups['all'] | length
  retries: 30
  delay: 15
