---
- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: true
    mode: '0755'
    owner: root
    group: root

- name: Run CIS-Hardening Tasks
  ansible.builtin.include_tasks: cis_hardening.yml

- name: Include task file for systemd environment configuration
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_systemd_env_config_file_path) }}"
    file_destination: "/etc/default/{{ service_name }}"
    file_description: "systemd env options"
    file_path: "{{ rke2_systemd_env_config_file_path }}"
    validate_yaml: false

- name: Include task file for registry configuration
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_registry_config_file_path) }}"
    file_destination: "/etc/rancher/rke2/registries.yaml"
    file_description: "registry configuration"
    file_path: "{{ rke2_registry_config_file_path }}"
    validate_yaml: true
  when: rke2_registry_config_file_path is defined and rke2_registry_config_file_path | length > 0

- name: Include task file for audit policy configuration
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_audit_policy_config_file_path) }}"
    file_destination: "/etc/rancher/rke2/audit-policy.yaml"
    file_description: "audit policy configuration"
    file_path: "{{ rke2_audit_policy_config_file_path }}"
    validate_yaml: true
  when:
    - inventory_hostname in groups['rke2_servers']
    - rke2_audit_policy_config_file_path is defined
    - rke2_audit_policy_config_file_path | length > 0

- name: Include task file for pod security admission config
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_pod_security_admission_config_file_path) }}"
    file_destination: "/etc/rancher/rke2/pod-security-admission-config.yaml"
    file_description: "pod security admission config"
    file_path: "{{ rke2_pod_security_admission_config_file_path }}"
    validate_yaml: true
  when:
    - inventory_hostname in groups['rke2_servers']
    - rke2_pod_security_admission_config_file_path is defined
    - rke2_pod_security_admission_config_file_path | length > 0

- name: Generate RKE2 main configuration using template
  ansible.builtin.template:
    src: rke2_config.yaml.j2
    dest: "/etc/rancher/rke2/config.yaml"
    mode: '0640'
    owner: root
    group: root
    backup: true
  notify: "Restart {{ service_name }}"

- name: Validate RKE2 configuration syntax
  ansible.builtin.shell: |
    python3 -c "
    import yaml
    try:
        with open('/etc/rancher/rke2/config.yaml', 'r') as f:
            config = yaml.safe_load(f)
        print('YAML syntax is valid')
        print(f'Configuration contains {len(config)} top-level keys')
        if 'helm-chart-values' in config:
            print(f'Found {len(config[\"helm-chart-values\"])} helm chart configurations')
    except yaml.YAMLError as e:
        print(f'YAML Error: {e}')
        exit(1)
    except Exception as e:
        print(f'File Error: {e}')
        exit(1)
    "
  register: yaml_validation
  changed_when: false
  failed_when: yaml_validation.rc != 0

- name: Show RKE2 configuration validation results
  ansible.builtin.debug:
    var: yaml_validation.stdout_lines
  when: ansible_verbosity >= 1

- name: Display RKE2 configuration summary
  ansible.builtin.debug:
    msg: |
      RKE2 Configuration Summary:
      - Node Type: {{ 'Server' if inventory_hostname in groups['rke2_servers'] else 'Agent' }}
      - Node IP: {{ rke2_node_ip | default(ansible_default_ipv4.address) }}
      - CNI: {{ rke2_cni | default('canal') }}
      - Cluster CIDR: {{ rke2_cluster_cidr | default('172.16.0.0/16') }}
      - Service CIDR: {{ rke2_service_cidr | default('172.17.0.0/16') }}
      {% if rke2_coredns_forwarders is defined %}
      - DNS Forwarders: {{ rke2_coredns_forwarders | join(', ') }}
      {% endif %}
      {% if rke2_canal_config is defined %}
      - Canal Interface: {{ rke2_canal_config.flannel.interface | default('ens192') }}
      - VXLAN Port: {{ rke2_canal_config.flannel.vxlan_port | default(8472) }}
      {% endif %}

- name: Start and enable RKE2 service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started
    enabled: true
  register: rke2_service_start
  retries: 3
  delay: 10
  until: rke2_service_start is succeeded

- name: Wait for RKE2 to be ready
  ansible.builtin.wait_for:
    port: 6443
    host: "{{ ansible_default_ipv4.address }}"
    delay: 30
    timeout: 300
  when: inventory_hostname in groups['rke2_servers']

- name: Verify RKE2 cluster status
  ansible.builtin.shell: |
    export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
    /var/lib/rancher/rke2/bin/kubectl get nodes
  register: cluster_status
  changed_when: false
  failed_when: false
  when: inventory_hostname in groups['rke2_servers'][0:1]

- name: Show cluster status
  ansible.builtin.debug:
    var: cluster_status.stdout_lines
  when:
    - cluster_status is defined
    - cluster_status.rc == 0
    - ansible_verbosity >= 1
