---
- name: Add pre-requisites
  ansible.builtin.apt:
    name:
      - python3-kubernetes

- name: Deploy Cilium HelmChartConfig
  ansible.builtin.template:
    src: rke2-cilium-config.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
    mode: '0644'
    owner: root
    group: root
  when:
    - inventory_hostname in groups['rke2_servers']
    - rke2_cni == "cilium"
    - rke2_cilium_config is defined
  notify: Restart rke2-server

- name: Deploy Calico HelmChartConfig
  ansible.builtin.template:
    src: rke2-calico-config.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-calico-config.yaml
    mode: '0644'
    owner: root
    group: root
  when:
    - inventory_hostname in groups['rke2_servers']
    - rke2_cni == "calico"
    - rke2_calico_config is defined
  notify: Restart rke2-server

- name: Deploy Flannel HelmChartConfig
  ansible.builtin.template:
    src: rke2-flannel-config.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-flannel-config.yaml
    mode: '0644'
    owner: root
    group: root
  when:
    - inventory_hostname in groups['rke2_servers']
    - rke2_cni == "flannel"
    - rke2_flannel_config is defined
  notify: Restart rke2-server

- name: Validate cluster CIDR format
  ansible.builtin.assert:
    that:
      - rke2_cluster_cidr | regex_search('^(\d{1,3}\.){3}\d{1,3}/\d{1,2}(,([0-9a-fA-F:]+)/\d{1,3})?$')
    fail_msg: "rke2_cluster_cidr must be in valid CIDR format (IPv4/prefix or IPv4/prefix,IPv6/prefix)"
    success_msg: "rke2_cluster_cidr format is valid"
  when: rke2_cluster_cidr is defined

- name: Validate service CIDR format
  ansible.builtin.assert:
    that:
      - rke2_service_cidr | regex_search('^(\d{1,3}\.){3}\d{1,3}/\d{1,2}(,([0-9a-fA-F:]+)/\d{1,3})?$')
    fail_msg: "rke2_service_cidr must be in valid CIDR format (IPv4/prefix or IPv4/prefix,IPv6/prefix)"
    success_msg: "rke2_service_cidr format is valid"
  when: rke2_service_cidr is defined

- name: Check for CIDR overlap
  ansible.builtin.assert:
    that:
      - rke2_cluster_cidr != rke2_service_cidr
    fail_msg: "rke2_cluster_cidr and rke2_service_cidr cannot be the same"
    success_msg: "No CIDR overlap detected"
  when:
    - rke2_cluster_cidr is defined
    - rke2_service_cidr is defined

- name: Display network configuration
  ansible.builtin.debug:
    msg:
      - "CNI Plugin: {{ rke2_cni }}"
      - "Cluster CIDR: {{ rke2_cluster_cidr }}"
      - "Service CIDR: {{ rke2_service_cidr }}"
  when: inventory_hostname == groups['rke2_servers'][0]
