---
- name: Read RKE2 config and extract token
  ansible.builtin.shell: awk '/token:/ {print $2; exit}' /etc/rancher/rke2/rke2.yaml
  register: rke2_token
  changed_when: false
  delegate_to: "{{ groups['masters'][0] }}"

- name: Wait for Kubernetes API to be ready
  ansible.builtin.uri:
    url: "https://{{ ansible_default_ipv4.address }}:6443/healthz"
    method: GET
    validate_certs: false
    status_code: 200
  register: api_check
  until: api_check.status == 200
  delegate_to: "{{ groups['masters'][0] }}"
  retries: 30
  delay: 10

- name: Create NSX system namespace
  kubernetes.core.k8s:
    name: nsx-system
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['masters'][0] }}"

- name: Create NSX operator ConfigMap
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nsx-ncp-operator-config
        namespace: nsx-system
      data:
        cluster: "{{ nsx_cluster_name }}"
        nsx_api_managers: "{{ nsx_manager_host }}"
        nsx_username: "{{ nsx_username }}"
        nsx_password: "{{ nsx_password }}"
        container_ip_blocks: "{{ nsx_container_ip_blocks }}"
        tier0_gateway: "{{ nsx_tier0_gateway }}"
        external_ip_pools: "{{ nsx_external_ip_pools }}"
        policy_nsxapi: "true"
        single_tier_topology: "true"
        cluster_cidr: "{{ cluster_cidr }}"
        service_cidr: "{{ service_cidr }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['masters'][0] }}"

- name: Create NSX operator RBAC
  kubernetes.core.k8s:
    definition: "{{ item }}"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['masters'][0] }}"
  loop:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: nsx-ncp-operator
        namespace: nsx-system
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: nsx-ncp-operator
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: nsx-ncp-operator
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: nsx-ncp-operator
      subjects:
        - kind: ServiceAccount
          name: nsx-ncp-operator
          namespace: nsx-system

- name: Deploy NSX Container Plugin Operator
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nsx-ncp-operator
        namespace: nsx-system
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nsx-ncp-operator
        template:
          metadata:
            labels:
              app: nsx-ncp-operator
          spec:
            serviceAccountName: nsx-ncp-operator
            containers:
              - name: nsx-ncp-operator
                image: "{{ nsx_operator_image }}"
                env:
                  - name: NCP_IMAGE
                    value: "{{ nsx_ncp_image }}"
                  - name: WATCH_NAMESPACE
                    value: ""
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: OPERATOR_NAME
                    value: "nsx-ncp-operator"
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['masters'][0] }}"

- name: Create NCPInstall Custom Resource
  kubernetes.core.k8s:
    definition:
      apiVersion: operator.nsx.vmware.com/v1
      kind: NCPInstall
      metadata:
        name: nsx-ncp
        namespace: nsx-system
      spec:
        addNodeTag: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['masters'][0] }}"

- name: Wait for NSX operator to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: nsx-ncp-operator
    namespace: nsx-system
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  register: operator_status
  until: operator_status.resources[0].status.readyReplicas == 1
  retries: 60
  delay: 10
  delegate_to: "{{ groups['masters'][0] }}"

- name: Verify NSX components are deployed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: DaemonSet
    namespace: nsx-system
    kubeconfig: /etc/rancher/rke2/rke2.yaml
  register: nsx_daemonsets
  delegate_to: "{{ groups['masters'][0] }}"

- name: Display NSX component status
  ansible.builtin.debug:
    msg: "NSX DaemonSets: {{ nsx_daemonsets.resources | map(attribute='metadata.name') | list }}"
