rke2_config:
  # Node labels for control plane nodes
  node-label:
    - "node-role.kubernetes.io/control-plane=true"
    - "node-role.kubernetes.io/master=true"
    - "node.kubernetes.io/instance-type=control-plane"
    - "cluster-role=server"
    - "workload-type=system"
  
  # Taints to prevent workload scheduling on control plane
  node-taint:
    - "node-role.kubernetes.io/control-plane=true:NoSchedule"
    - "CriticalAddonsOnly=true:NoExecute"